remove obsolete numpy aliases `np.bool` and `np.float`
This basically fixes the following error that many people encountered:

```
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'float_'?
```

Migth not work with veeery old versions of numpy but I guess that requiring
>=1.20 is quite safe nowadays.

Ref.:
https://github.com/matthiaskoenig/fbc_curation/issues/98